apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress_alpine_esou
        ports:
        - containerPort: 5050
        imagePullPolicy: Never
        env:
          - name: DB_NAME
            value: wordpress
          - name: DB_USER
            value: root
          - name: DB_PASSWORD
            value: password
          - name: DB_HOST
            value: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  type: NodePort
  ports:
  - port: 5050
    nodePort: 5050
    protocol: TCP
    name: http
  selector:
    app: wordpress